"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import drink as shared_drink
from ...models.shared import drinktype as shared_drinktype
from ...models.shared import error as shared_error
from typing import List, Optional

LIST_DRINKS_SERVERS = [
	"https://speakeasy.bar",
	"https://test.speakeasy.bar",
]


@dataclasses.dataclass
class ListDrinksRequest:
    drink_type: Optional[shared_drinktype.DrinkType] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'drinkType', 'style': 'form', 'explode': True }})
    r"""The type of drink to filter by. If not provided all drinks will be returned."""
    



@dataclasses.dataclass
class ListDrinksResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    classes: Optional[List[shared_drink.Drink]] = dataclasses.field(default=None)
    r"""A list of drinks."""
    error: Optional[shared_error.Error] = dataclasses.field(default=None)
    r"""An unknown error occurred interacting with the API."""
    

