"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import drink as shared_drink
from ...models.shared import error as shared_error
from ...models.shared import ingredient as shared_ingredient
from dataclasses_json import Undefined, dataclass_json
from speakeasybar import utils
from typing import Optional


@dataclasses.dataclass
class StockUpdateResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    error: Optional[shared_error.Error] = dataclasses.field(default=None)
    r"""An unknown error occurred interacting with the API."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class StockUpdateRequestBody:
    drink: Optional[shared_drink.DrinkInput] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('drink'), 'exclude': lambda f: f is None }})
    ingredient: Optional[shared_ingredient.IngredientInput] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('ingredient'), 'exclude': lambda f: f is None }})
    

