/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config";
import * as enc$ from "../lib/encodings";
import { HTTPClient } from "../lib/http";
import { ClientSDK, RequestOptions } from "../lib/sdks";
import * as models from "../models";

export class Drinks extends ClientSDK {
    private readonly options$: SDKOptions;

    constructor(options: SDKOptions = {}) {
        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
        });

        this.options$ = options;
        void this.options$;
    }
    /**
     * Get a drink.
     *
     * @remarks
     * Get a drink by name, if authenticated this will include stock levels and product codes otherwise it will only include public information.
     */
    async getDrink(name: string, options?: RequestOptions): Promise<models.GetDrinkResponse> {
        const input: models.GetDrinkRequest = {
            name: name,
        };
        const headers = new Headers();
        headers.set("user-agent", SDK_METADATA.userAgent);
        headers.set("Accept", "application/json");

        const payload = models.GetDrinkRequest$.outboundSchema.parse(input);
        const body = null;

        const pathParams = {
            name: enc$.encodeSimple("name", payload.name, {
                explode: false,
                charEncoding: "percent",
            }),
        };

        const path = this.templateURLComponent("/drink/{name}")(pathParams);

        const security =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;
        const securitySettings = this.resolveGlobalSecurity(security);

        const response = await this.fetch$(
            { security: securitySettings, method: "get", path, headers, body },
            options
        );

        const responseFields = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = models.GetDrinkResponse$.inboundSchema.parse({
                ...responseFields,
                Drink: responseBody,
            });
            return result;
        } else if (this.matchResponse(response, "5XX", "application/json")) {
            const responseBody = await response.json();
            const result = models.APIError$.inboundSchema.parse({
                ...responseFields,
                ...responseBody,
            });
            throw new models.APIError(result);
        } else if (this.matchResponse(response, "default", "application/json")) {
            const responseBody = await response.json();
            const result = models.GetDrinkResponse$.inboundSchema.parse({
                ...responseFields,
                Error: responseBody,
            });
            return result;
        } else {
            const responseBody = await response.text();
            throw new models.SDKError("Unexpected API response", response, responseBody);
        }
    }

    /**
     * Get a list of drinks.
     *
     * @remarks
     * Get a list of drinks, if authenticated this will include stock levels and product codes otherwise it will only include public information.
     */
    async listDrinks(
        drinkType?: models.DrinkType | undefined,
        options?: RequestOptions & { serverURL?: string }
    ): Promise<models.ListDrinksResponse> {
        const input: models.ListDrinksRequest = {
            drinkType: drinkType,
        };
        const headers = new Headers();
        headers.set("user-agent", SDK_METADATA.userAgent);
        headers.set("Accept", "application/json");

        const payload = models.ListDrinksRequest$.outboundSchema.parse(input);
        const body = null;

        const path = this.templateURLComponent("/drinks")();

        const query = [
            enc$.encodeForm("drinkType", payload.drinkType, {
                explode: true,
                charEncoding: "percent",
            }),
        ]
            .filter(Boolean)
            .join("&");

        const baseURL =
            options?.serverURL ||
            this.templateURLComponent(models.ListDrinksServerList[0], {
                charEncoding: "percent",
            })();

        const security =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;
        const securitySettings = this.resolveGlobalSecurity(security);

        const response = await this.fetch$(
            { security: securitySettings, method: "get", baseURL, path, headers, query, body },
            options
        );

        const responseFields = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = models.ListDrinksResponse$.inboundSchema.parse({
                ...responseFields,
                classes: responseBody,
            });
            return result;
        } else if (this.matchResponse(response, "5XX", "application/json")) {
            const responseBody = await response.json();
            const result = models.APIError$.inboundSchema.parse({
                ...responseFields,
                ...responseBody,
            });
            throw new models.APIError(result);
        } else if (this.matchResponse(response, "default", "application/json")) {
            const responseBody = await response.json();
            const result = models.ListDrinksResponse$.inboundSchema.parse({
                ...responseFields,
                Error: responseBody,
            });
            return result;
        } else {
            const responseBody = await response.text();
            throw new models.SDKError("Unexpected API response", response, responseBody);
        }
    }
}
