/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKOptions, serverURLFromOptions } from "../lib/config";
import { HTTPClient } from "../lib/http";
import { ClientSDK } from "../lib/sdks";
import { Authentication } from "./authentication";
import { Config } from "./config";
import { Drinks } from "./drinks";
import { Ingredients } from "./ingredients";
import { Orders } from "./orders";

export class Speakeasybar extends ClientSDK {
    private readonly options$: SDKOptions;

    constructor(options: SDKOptions = {}) {
        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
        });

        this.options$ = options;
        void this.options$;
    }

    private _authentication?: Authentication;
    get authentication() {
        return (this._authentication ??= new Authentication(this.options$));
    }

    private _drinks?: Drinks;
    get drinks() {
        return (this._drinks ??= new Drinks(this.options$));
    }

    private _ingredients?: Ingredients;
    get ingredients() {
        return (this._ingredients ??= new Ingredients(this.options$));
    }

    private _orders?: Orders;
    get orders() {
        return (this._orders ??= new Orders(this.options$));
    }

    private _config?: Config;
    get config() {
        return (this._config ??= new Config(this.options$));
    }
}
