/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export class RFCDate {
  private date: Date;

  static today() {
    return new RFCDate(new Date());
  }

  constructor(date: Date | string) {
    this.date = new Date(date);
  }

  toJSON(): string {
    return this.toString();
  }

  toString(): string {
    const year = this.date.getFullYear();
    const month = `${this.date.getMonth() + 1}`.padStart(2, "0");
    const day = `${this.date.getDate()}`.padStart(2, "0");

    return `${year}-${month}-${day}`;
  }
}
