/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

/**
 * The type of ingredient.
 */
export enum IngredientType {
    Fresh = "fresh",
    LongLife = "long-life",
    Packaged = "packaged",
}

/** @internal */
export const IngredientType$ = z.nativeEnum(IngredientType);
