/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ErrorT, ErrorT$ } from "./error";
import { Ingredient, Ingredient$ } from "./ingredient";
import { z } from "zod";

export type ListIngredientsRequest = {
    /**
     * A list of ingredients to filter by. If not provided all ingredients will be returned.
     */
    ingredients?: Array<string> | undefined;
};

export type ListIngredientsResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * An unknown error occurred interacting with the API.
     */
    error?: ErrorT | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * A list of ingredients.
     */
    classes?: Array<Ingredient> | undefined;
};

/** @internal */
export namespace ListIngredientsRequest$ {
    export type Inbound = {
        ingredients?: Array<string> | undefined;
    };

    export const inboundSchema: z.ZodType<ListIngredientsRequest, z.ZodTypeDef, Inbound> = z
        .object({
            ingredients: z.array(z.string()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.ingredients === undefined ? null : { ingredients: v.ingredients }),
            };
        });

    export type Outbound = {
        ingredients?: Array<string> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListIngredientsRequest> = z
        .object({
            ingredients: z.array(z.string()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.ingredients === undefined ? null : { ingredients: v.ingredients }),
            };
        });
}

/** @internal */
export namespace ListIngredientsResponse$ {
    export type Inbound = {
        ContentType: string;
        Error?: ErrorT$.Inbound | undefined;
        StatusCode: number;
        RawResponse: Response;
        classes?: Array<Ingredient$.Inbound> | undefined;
    };

    export const inboundSchema: z.ZodType<ListIngredientsResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            Error: ErrorT$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            classes: z.array(Ingredient$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.Error === undefined ? null : { error: v.Error }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.classes === undefined ? null : { classes: v.classes }),
            };
        });

    export type Outbound = {
        ContentType: string;
        Error?: ErrorT$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
        classes?: Array<Ingredient$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListIngredientsResponse> = z
        .object({
            contentType: z.string(),
            error: ErrorT$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            classes: z.array(Ingredient$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                ...(v.error === undefined ? null : { Error: v.error }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.classes === undefined ? null : { classes: v.classes }),
            };
        });
}
