/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { OrderType, OrderType$ } from "./ordertype";
import { z } from "zod";

/**
 * The status of the order.
 */
export enum Status {
    Pending = "pending",
    Processing = "processing",
    Complete = "complete",
}

/**
 * An order for a drink or ingredient.
 */
export type Order = {
    /**
     * The product code of the drink or ingredient.
     */
    productCode: string;
    /**
     * The number of units of the drink or ingredient to order.
     */
    quantity: number;
    /**
     * The status of the order.
     */
    status: Status;
    /**
     * The type of order.
     */
    type: OrderType;
};

/** @internal */
export const Status$ = z.nativeEnum(Status);

/** @internal */
export namespace Order$ {
    export type Inbound = {
        productCode: string;
        quantity: number;
        status: Status;
        type: OrderType;
    };

    export const inboundSchema: z.ZodType<Order, z.ZodTypeDef, Inbound> = z
        .object({
            productCode: z.string(),
            quantity: z.number().int(),
            status: Status$,
            type: OrderType$,
        })
        .transform((v) => {
            return {
                productCode: v.productCode,
                quantity: v.quantity,
                status: v.status,
                type: v.type,
            };
        });

    export type Outbound = {
        productCode: string;
        quantity: number;
        status: Status;
        type: OrderType;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Order> = z
        .object({
            productCode: z.string(),
            quantity: z.number().int(),
            status: Status$,
            type: OrderType$,
        })
        .transform((v) => {
            return {
                productCode: v.productCode,
                quantity: v.quantity,
                status: v.status,
                type: v.type,
            };
        });
}
